package com.wormhole_xtreme.wormhole.config;
import com.wormhole_xtreme.wormhole.config.ConfigManager.ConfigKeys;

/**
 * The Class DefaultSettings.
 * Based on class "SettingsList" from MinecartMania by Afforess.
 */
class DefaultSettings
{

    /** The Constant config. */
    final static Setting[] config = {
        new Setting(ConfigKeys.TIMEOUT_ACTIVATE, 30, "Number of seconds after a gate is activated, but before dialing before timing out.", "WormholeXTreme"),
        new Setting(ConfigKeys.TIMEOUT_SHUTDOWN, 38, "Number of seconds after a gate is dialed before automatically shutdown. With 0 timeout a gate won't shutdown until something goes through the gate.", "WormholeXTreme"),
        new Setting(ConfigKeys.MAX_OPEN_SECONDS, 300, "Longest a wormhole may stay open, in seconds, however often it is re-dialled. Dialling restarts the shutdown timer, so without this a gate re-triggered on a schedule (a minecart over a detector rail, for example) would stay open forever and lock everyone else out. Measured from when the wormhole first opened. Set 0 for no limit.", "WormholeXTreme"),
        new Setting(ConfigKeys.USE_COOLDOWN_ENABLED, false, "Enable Cooldown timers on stargate usage. Timer only activates on passage through wormholes.", "WormholeXTreme"),
        new Setting(ConfigKeys.USE_COOLDOWN_SECONDS, 120, "Seconds a player must wait between gate trips, when the cooldown above is enabled. This replaced three per-group settings that were never registered here, so none of them could be read or written and the cooldown was stuck at this value however it was set.", "WormholeXTreme"),
        new Setting(ConfigKeys.PERMISSIONS_SUPPORT_DISABLE, false, "If set to true, Permissions plugin will not be attached to even if available.", "WormholeXTreme"),
        new Setting(ConfigKeys.PERMISSIONS_AUTO_FALLBACK, true, "If true and no Vault provider is detected, automatically fall back to simple permission mode.", "WormholeXTreme"),
        new Setting(ConfigKeys.WORMHOLE_USE_IS_TELEPORT, false, "The wormhole.use (or wormhole.simple.use) permission means that a user can teleport through gate. When false a user will be able to teleport but not activate a gate. When true only users with wormhole.use (or wormhole.simple.use) can even teleport.", "WormholeXTreme"),
        new Setting(ConfigKeys.HELP_SUPPORT_DISABLE, false, "If set to true, Help plugin will not be attached to even if available.", "WormholeXTreme"),
        new Setting(ConfigKeys.SAME_WORLD_ONLY, false, "If set to true, players may only teleport through gates whose destination is in the same world. Cross-world travel will be blocked.", "WormholeXTreme"),
        new Setting(ConfigKeys.LOG_LEVEL, "INFO", "Log level to use for minecraft logging purposes. Values are SEVERE, WARNING, INFO, CONFIG, FINE, FINER, and FINEST. In order of least to most logging output.", "WormholeXTreme"),
        new Setting(ConfigKeys.ENTITY_SCAN_INTERVAL_TICKS, 20, "Tick interval for periodic non-player entity scan near gates. Higher values reduce server load.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_COUNTDOWN_TICKS, 60, "Ticks a transport ring counts down before it commits. Below about 20 the abort window stops being real and rings take people walking past.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_COOLDOWN_TICKS, 1200, "Ticks a ring pair refuses to fire again after a cycle. Shared by both ends.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_DEPLOY_TICKS, 2, "Ticks between frames of the ring deploy and retract animations.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_SETTLE_TICKS, 20, "Ticks the fully deployed ring stack stands still before the teleport fires. One second by default.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_FLASH_TICKS, 3, "Ticks each ring stays lit as the transport flash runs through the stack.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_LIGHTS_LINGER_TICKS, 20, "Ticks the ring pad stays lit after the last ring has sunk back into it. One second by default.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_OUTLINE_ON_REFUSAL, true, "Briefly light a ring's pattern for a player it turns away, so they can see where it is. Idle rings are invisible.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_OUTLINE_TICKS, 40, "How long that outline stays visible, in ticks.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_HOLD_TICKS, 20, "Ticks the ring stack stands still once the light has finished, before it retracts.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_REACH, 4, "Block layers of passenger volume, from the ring plane into the room. Matters most for ceiling rings.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_MIN_SEPARATION, 8, "Required distance between ring anchors, in blocks. Overlap is refused regardless of this.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_MAX_LINK_DISTANCE, 256, "Furthest apart the two ends of a ring pair may be on the ground, in blocks. 256 is sixteen chunks: the whole of one base, nowhere near town to town. Gates are the long-haul option. Zero means no limit.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_MAX_CEILING_DROP, 10, "How far below its plane a ceiling ring will look for the floor, in blocks. Its rings drop all the way down and stack up from there, so it needs a floor near enough to reach.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_MAX_LINK_HEIGHT, 384, "Furthest apart the two ends of a ring pair may be in height, in blocks. 384 is the full height of the world, so bedrock to build limit is always allowed - going straight down is what rings are for. Zero means no limit.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_MAX_PAIRS_PER_PLAYER, 10, "How many ring pairs one player may own. Zero means no limit.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_DEFAULT_ACCESS, "PRIVATE", "What a newly built ring pair starts as: PUBLIC or PRIVATE.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_DEFAULT_STYLE, "CONCURRENT", "How a ring stack deploys: CONCURRENT (all at once) or SEQUENTIAL (one at a time).", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_DEFAULT_MATERIAL, "SMOOTH_STONE_SLAB", "Fallback ring material, and what a ring is drawn in if the slab it was laid in cannot be read. Normally unused: a ring keeps whatever slab it was built from. SMOOTH_STONE_SLAB is the plain stone slab people picture, not STONE_SLAB, which is the rougher raw-stone one.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_DEFAULT_LIGHT, "GLOWSTONE", "What the ring pad lights up as while it is working.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUNDS_ENABLED, true, "Whether stargates make any noise. Everything below is ignored when this is false.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_VOLUME, 1.5, "How loud gate sounds are. Bukkit scales audible range with volume, so this is a distance knob too: 1.5 carries about twenty-four blocks, which suits something people walk towards.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_ACTIVATE, "block.conduit.activate", "Played as a gate begins to dial. Set to none for silence. Any sound name the client knows works, including one from a resource pack.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_CHEVRON, "block.iron_trapdoor.close", "Played once per chevron as it locks, pitch climbing through the sequence so the gate sounds like it is working towards something.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_KAWOOSH, "entity.player.splash.high_speed", "Played once as the wormhole establishes and the woosh rolls out. A kawoosh is a surge of water bursting out of the ring, so this is the heavy splash, pitched down for size. Set to none for silence.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_CLOSE, "block.conduit.deactivate", "Played as a wormhole closes.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_IRIS_CLOSE, "block.iron_door.close", "The iris closing over a gate. Pitched down a little, since it is a shield rather than a door. Set to none for silence.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_IRIS_OPEN, "block.iron_door.open", "The iris opening. Set to none for silence.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_AMBIENT, "ambient.underwater.loop", "The soft running water an open wormhole makes while it stands there, as in the show. Set to none for silence.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_SOUND_AMBIENT_TICKS, 70, "How often the ambient water repeats, in ticks. A little under the length of the default sound, so it runs continuously rather than in gasps.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_ARRIVAL_SPLASH_TICKS, 20, "Ticks a traveller sees water as they come out of a gate, as though surfacing from the event horizon. One second by default. Drawn to that player alone at eye height and nothing is written to the world. This is also how long it keeps being redrawn, because arriving hands the client fresh chunks that erase anything drawn before them - so a very distant trip may still finish loading after the window and miss it, and raising this widens the window. Raise it too far and the client starts predicting that it is swimming; 0 turns it off.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_SOUNDS_ENABLED, true, "Whether rings make any noise. Everything below is ignored when this is false.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_SOUND_VOLUME, 1.0, "How loud ring sounds are. Bukkit scales audible range with volume, so this is a distance knob too: 1.0 is heard about sixteen blocks away.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_SOUND_OPEN, "block.beacon.activate", "Played at both ends as the pad opens and the countdown starts. Set to none for silence. Any sound name the client knows works, including one from a resource pack.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_SOUND_RING, "block.piston.extend", "Played once per ring as it leaves the pad, and again as it returns. The pitch climbs with the stack going out and falls coming back, which is what makes it read as movement.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_SOUND_FLASH, "block.beacon.power_select", "Played at both ends at the moment of transport.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_SOUND_CLOSE, "block.beacon.deactivate", "Played at both ends as the pad closes.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_SOUND_REFUSED, "block.note_block.bass", "Played to a player a ring turns away, wherever they are standing. Heard by them alone.", "WormholeXTreme"),
        new Setting(ConfigKeys.RING_DEFAULT_FLASH, "GLOWSTONE", "What a ring turns to as the transport light passes through it. Set it apart from the pad light to make the transport its own moment.", "WormholeXTreme"),
        new Setting(ConfigKeys.GATE_MATERIAL_GROUPS_AUTODISCOVER, true, "When a gate shape uses a frame material no material group claims, add that palette to gate-material-groups automatically. Only unambiguous palettes are added: if two shapes share a frame material but disagree on their other materials, neither is added. Set false to curate the list by hand.", "WormholeXTreme"),
        new Setting(ConfigKeys.ECONOMY_ENABLED, false, "Enable Vault economy integration. Requires Vault and an economy plugin (e.g. EssentialsX). When false all economy features are disabled regardless of cost settings.", "WormholeXTreme"),
        new Setting(ConfigKeys.ECONOMY_USE_COST, 0.0, "Amount charged to a player each time they walk through a gate. Set to 0.0 to disable use cost.", "WormholeXTreme"),
        new Setting(ConfigKeys.ECONOMY_BUILD_COST, 0.0, "Amount charged to a player when they successfully build a new gate. Set to 0.0 to disable build cost.", "WormholeXTreme"),
        new Setting(ConfigKeys.SIGN_GLOWING_TEXT, false, "Whether the plugin's own sign text glows. Glow draws a bright outline around every character, which on top of a coloured line reads as a hard-to-read halo -- so this is off, and the colours below carry the emphasis instead. Set true if you want signs legible from further away in a dark gate room and can live with that.", "WormholeXTreme"),
        new Setting(ConfigKeys.REDSTONE_EXTEND_OPEN_TIME, true, "Whether a redstone signal on a gate that is already open pushes its shutdown back, instead of doing nothing. Never past max_open_seconds, which is measured from when the wormhole first opened and is not affected by this -- so a cart crossing a detector rail can keep a gate open while traffic is flowing, but still cannot hold it open indefinitely.", "WormholeXTreme"),
        new Setting(ConfigKeys.SIGN_DIAL_MATCH_MATERIAL, true, "Whether a player-placed dial sign is converted to the gate's own sign material, so a themed gate does not end up with an oak dial sign on a crimson frame. The sign's text and facing are kept. Set false to leave whatever sign the player put up exactly as they placed it.", "WormholeXTreme"),
        new Setting(ConfigKeys.SIGN_COLOR_GATE_NAME, "DARK_AQUA", "Colour of a gate's own name, on both its name sign and its dial sign. Any Bukkit colour name; anything unrecognised falls back to the default.", "WormholeXTreme"),
        new Setting(ConfigKeys.SIGN_COLOR_NETWORK, "GRAY", "Colour of the network line on a gate's name sign.", "WormholeXTreme"),
        new Setting(ConfigKeys.SIGN_COLOR_OWNER, "GRAY", "Colour of the owner line on a gate's name sign.", "WormholeXTreme"),
        new Setting(ConfigKeys.SIGN_COLOR_SELECTED, "DARK_GREEN", "Colour of the destination currently selected on a dial sign. Kept distinct from the neighbours either side of it, since telling those apart at a glance is the whole point of the dial sign.", "WormholeXTreme"),
        new Setting(ConfigKeys.SIGN_COLOR_NEIGHBOUR, "GRAY", "Colour of the destinations either side of the selected one on a dial sign.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_SOUNDS_ENABLED, true, "Whether beaming makes any noise. Everything below is ignored when this is false.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_SOUND_VOLUME, 1.0, "How loud beam sounds are. Bukkit scales audible range with volume, so this is a distance knob too: 1.0 is heard about sixteen blocks away.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_SOUND_CHARGE, "block.respawn_anchor.charge", "Played the instant a beam sequence starts.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_SOUND_DEPART, "entity.enderman.teleport", "Played the instant the real teleport fires, partway through the rise.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_SOUND_ARRIVE, "entity.shulker.teleport", "Played once the column finishes descending at the destination.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_ENVELOP_TICKS, 12, "How long, in ticks, the glow gathers at body height before opening into the departure column.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_VANISH_AT_STEP, 6, "How far into the envelope, in ticks, the traveller vanishes. Clamped inside it at run time, whatever this is set to.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_RISE_TICKS, 18, "How long, in ticks, the column rises and departs once the envelope opens into it.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_TELEPORT_AT_STEP, 12, "How far into the rise, in ticks, the real teleport fires. Clamped inside the rise at run time, whatever this is set to.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_DESCEND_TICKS, 20, "How long, in ticks, the column takes to descend into place at the destination.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_FADE_TICKS, 8, "How long, in ticks, the column takes to fade out once it has deposited the traveller.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_USE_COOLDOWN_ENABLED, false, "Whether beam travel has a per-player cooldown at all.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_USE_COOLDOWN_SECONDS, 120, "Seconds a player must wait between beams, when the cooldown above is enabled.", "WormholeXTreme"),
        new Setting(ConfigKeys.BEAM_ECONOMY_USE_COST, 0.0, "Amount charged to a player each time they beam. Set to 0.0 to disable. Uses the same Vault connection as gate costs -- ECONOMY_ENABLED must also be true.", "WormholeXTreme")
    };

}

