'use strict';
// Declarative geometry compiled to commands. A Blueprint is an ordered list of fills and
// setblocks for one datapack function; the compiler splits any fill over the vanilla limit
// and never uses `fill ... hollow` (a hollow fill counts its whole volume, and splitting one
// leaves floors across doorways), so a room is laid wall by wall.

const campus = require('./campus');
const text = require('./text');

const FILL_LIMIT = 32768;

function box3(x0, y0, z0, x1, y1, z1) {
  return {
    x0: Math.min(x0, x1), y0: Math.min(y0, y1), z0: Math.min(z0, z1),
    x1: Math.max(x0, x1), y1: Math.max(y0, y1), z1: Math.max(z0, z1),
  };
}

function volume(b) {
  return (b.x1 - b.x0 + 1) * (b.y1 - b.y0 + 1) * (b.z1 - b.z0 + 1);
}

/** Halves the longest axis until every piece is within the fill limit. */
function split(b, limit = FILL_LIMIT) {
  if (volume(b) <= limit) return [b];
  const spans = [['x', b.x1 - b.x0], ['y', b.y1 - b.y0], ['z', b.z1 - b.z0]].sort((p, q) => q[1] - p[1]);
  const axis = spans[0][0];
  const mid = Math.floor((b[`${axis}0`] + b[`${axis}1`]) / 2);
  return [...split({ ...b, [`${axis}1`]: mid }, limit), ...split({ ...b, [`${axis}0`]: mid + 1 }, limit)];
}

function overlaps(a, b) {
  return a.x0 <= b.x1 && b.x0 <= a.x1 && a.y0 <= b.y1 && b.y0 <= a.y1 && a.z0 <= b.z1 && b.z0 <= a.z1;
}

/** The interior of a campus box as a 3-D box. */
function interior(room) {
  return box3(room.x0, room.y0, room.z0, room.x1, room.y0 + Math.max(room.h, 1) - 1, room.z1);
}

class Blueprint {
  constructor(name, dim) {
    this.name = name;
    this.dim = dim;
    this.ops = [];
    this.anchors = []; // { at, block, what }: blocks the self-test reads back
    this.clear = []; // { id, box }: volumes that must be air once built
    this.keep = []; // { id, box }: volumes no decoration may touch (see wings/decor/guard.js)
    this.decorating = false;
  }

  fill(b, block) { this.ops.push({ kind: 'fill', box: b, block, decor: this.decorating }); return this; }
  set(x, y, z, block) { this.ops.push({ kind: 'set', at: [x, y, z], block, decor: this.decorating }); return this; }

  /** Runs `fn` with every block op it emits marked as decoration, for the guardrail. */
  decorate(fn) {
    this.decorating = true;
    try { fn(); } finally { this.decorating = false; }
    return this;
  }

  keepClear(id, b) { this.keep.push({ id, box: b }); return this; }

  /**
   * The block volumes the decoration wrote, and the block each thing it summoned stands in (a
   * plaque or a console's label): an entity in a cell is in a test's way as much as a block.
   */
  decorBoxes() {
    const out = [];
    for (const o of this.ops.filter((x) => x.decor)) {
      if (o.kind === 'fill') out.push({ box: o.box, block: o.block });
      else if (o.kind === 'set') out.push({ box: box3(...o.at, ...o.at), block: o.block });
      else {
        const m = /^summon (\S+) (-?[\d.]+) (-?[\d.]+) (-?[\d.]+)/.exec(o.line);
        if (!m) throw new Error(`${this.name}: a decoration command the guardrail cannot place: ${o.line.slice(0, 80)}`);
        const [x, y, z] = m.slice(2).map((s) => Math.floor(Number(s)));
        out.push({ box: box3(x, y, z, x, y, z), block: m[1], entity: true });
      }
    }
    return out;
  }
  cmd(line) { this.ops.push({ kind: 'cmd', line, decor: this.decorating }); return this; }
  anchor(x, y, z, block, what) { this.anchors.push({ at: [x, y, z], block, what, decor: this.decorating }); return this; }
  mustBeClear(id, b) { this.clear.push({ id, box: b }); return this; }

  /** Every block volume this blueprint writes, for the forceload and overlap checks. */
  boxes() {
    return this.ops.filter((o) => o.kind !== 'cmd').map((o) => (o.kind === 'fill' ? o.box : box3(...o.at, ...o.at)));
  }

  /** The function body; `sentinel` is reset first and set last. */
  compile(sentinel) {
    const lines = [`# ${this.name}: generated by scripts/facility/lib/blueprint.js; do not edit`];
    const s = sentinel ? `${sentinel.at.join(' ')}` : null;
    if (s) lines.push(`setblock ${s} minecraft:stone`);
    let blocks = 0;
    for (const o of this.ops) {
      if (o.kind === 'fill') {
        for (const p of split(o.box)) {
          lines.push(`fill ${p.x0} ${p.y0} ${p.z0} ${p.x1} ${p.y1} ${p.z1} ${o.block}`);
          blocks += volume(p);
        }
      } else if (o.kind === 'set') {
        lines.push(`setblock ${o.at.join(' ')} ${o.block}`);
        blocks += 1;
      } else lines.push(o.line);
    }
    if (s) lines.push(`setblock ${s} ${campus.PALETTE.sentinel}`);
    return { body: `${lines.join('\n')}\n`, commands: lines.length - 1, blocks };
  }
}

// ---- rooms and circulation -------------------------------------------------------------------

const P = campus.PALETTE;

/** A room laid wall by wall: optional floor, four walls with a skirting row, a roof. */
function room(bp, r, { wall = P.wall, roof = P.roof, floor = null, skirting = P.skirting } = {}) {
  const { x0, x1, z0, z1, y0, h } = r;
  const top = y0 + h - 1;
  if (floor) bp.fill(box3(x0 - 1, y0 - 1, z0 - 1, x1 + 1, y0 - 1, z1 + 1), floor);
  bp.fill(box3(x0 - 1, y0, z0 - 1, x1 + 1, top, z0 - 1), wall); // north
  bp.fill(box3(x0 - 1, y0, z1 + 1, x1 + 1, top, z1 + 1), wall); // south
  bp.fill(box3(x0 - 1, y0, z0, x0 - 1, top, z1), wall); // west
  bp.fill(box3(x1 + 1, y0, z0, x1 + 1, top, z1), wall); // east
  if (skirting) {
    bp.fill(box3(x0 - 1, y0, z0 - 1, x1 + 1, y0, z0 - 1), skirting);
    bp.fill(box3(x0 - 1, y0, z1 + 1, x1 + 1, y0, z1 + 1), skirting);
    bp.fill(box3(x0 - 1, y0, z0, x0 - 1, y0, z1), skirting);
    bp.fill(box3(x1 + 1, y0, z0, x1 + 1, y0, z1), skirting);
  }
  if (roof) bp.fill(box3(x0 - 1, top + 1, z0 - 1, x1 + 1, top + 1, z1 + 1), roof);
  bp.anchor(x0 - 1, y0 + Math.min(1, h - 1), z0 - 1, wall, 'north-west wall');
  if (roof) bp.anchor(x1 + 1, top + 1, z1 + 1, roof, 'south-east roof corner');
}

/** The doorway boxes a corridor cuts through the walls at its two ends. */
function corridorDoorways(c) {
  const { x0, x1, z0, z1, y0 } = c.box;
  const half = c.doorHalf || 2;
  const h = 4;
  if (c.axis === 'z') {
    const mx = Math.floor((x0 + x1) / 2);
    return [z0 - 1, z1 + 1].map((z) => box3(mx - half, y0, z, mx + half, y0 + h - 1, z));
  }
  const mz = Math.floor((z0 + z1) / 2);
  return [x0 - 1, x1 + 1].map((x) => box3(x, y0, mz - half, x, y0 + h - 1, mz + half));
}

/** A corridor: side walls and roof, a guide line down the middle, the colour along each side. */
function corridor(bp, c, colour) {
  const { x0, x1, z0, z1, y0, h } = c.box;
  const top = y0 + h - 1;
  const stripe = `minecraft:${colour}_concrete`;
  if (c.axis === 'z') {
    bp.fill(box3(x0 - 1, y0, z0, x0 - 1, top, z1), P.wall);
    bp.fill(box3(x1 + 1, y0, z0, x1 + 1, top, z1), P.wall);
    bp.fill(box3(x0 - 1, top + 1, z0, x1 + 1, top + 1, z1), P.roof);
    const mx = Math.floor((x0 + x1) / 2);
    bp.fill(box3(mx, y0 - 1, z0, mx, y0 - 1, z1), P.guide);
    bp.fill(box3(x0, y0 - 1, z0, x0, y0 - 1, z1), stripe);
    bp.fill(box3(x1, y0 - 1, z0, x1, y0 - 1, z1), stripe);
  } else {
    bp.fill(box3(x0, y0, z0 - 1, x1, top, z0 - 1), P.wall);
    bp.fill(box3(x0, y0, z1 + 1, x1, top, z1 + 1), P.wall);
    bp.fill(box3(x0, top + 1, z0 - 1, x1, top + 1, z1 + 1), P.roof);
    const mz = Math.floor((z0 + z1) / 2);
    bp.fill(box3(x0, y0 - 1, mz, x1, y0 - 1, mz), P.guide);
    bp.fill(box3(x0, y0 - 1, z0, x1, y0 - 1, z0), stripe);
    bp.fill(box3(x0, y0 - 1, z1, x1, y0 - 1, z1), stripe);
  }
}

// ---- chambers ------------------------------------------------------------------------------

// `yaw` is the direction you face looking out through that side (Minecraft: 0 south, 90 west).
const SIDES = {
  n: { axis: 'z', sign: -1, yaw: 180 },
  s: { axis: 'z', sign: 1, yaw: 0 },
  w: { axis: 'x', sign: -1, yaw: 90 },
  e: { axis: 'x', sign: 1, yaw: -90 },
};

/**
 * Where a cell's parts go, derived from its box and its door and gallery sides:
 *   wall(side)   the wall plane coordinate on that side;
 *   door         the doorway's blocks and the points just outside and inside it;
 *   board        over the door, outside;  pylon: two blocks along the wall from the door;
 *   gallery      a walkway one high and three deep outside the gallery wall;
 *   seat         the middle of the gallery, one up, facing in.
 */
function cellLayout(ch) {
  const b = ch.box;
  const top = b.y0 + b.h - 1;
  const wall = { n: b.z0 - 1, s: b.z1 + 1, w: b.x0 - 1, e: b.x1 + 1 };
  const mid = { x: Math.floor((b.x0 + b.x1) / 2), z: Math.floor((b.z0 + b.z1) / 2) };
  const out = (side, d) => (SIDES[side].sign * d);
  const at = (side, along, d) => (SIDES[side].axis === 'z'
    ? { x: along, z: wall[side] + out(side, d) }
    : { x: wall[side] + out(side, d), z: along });
  const doorAlong = SIDES[ch.door].axis === 'z' ? mid.x : mid.z;
  const door = {
    blocks: [0, 1].map((k) => at(ch.door, doorAlong + k, 0)),
    outside: at(ch.door, doorAlong, 2),
    inside: at(ch.door, doorAlong, -2),
    height: Math.min(3, b.h),
  };
  const boardAt = at(ch.door, doorAlong, 1);
  const pylonAt = at(ch.door, doorAlong - 2, 1);
  // The gallery: three rows outside the gallery wall, along its full length plus one each end.
  const g = ch.gallery;
  let gallery;
  if (SIDES[g].axis === 'z') {
    const z0 = wall[g] + out(g, 1);
    const z1 = wall[g] + out(g, 3);
    gallery = box3(b.x0 - 1, b.y0, z0, b.x1 + 1, b.y0, z1);
  } else {
    const x0 = wall[g] + out(g, 1);
    const x1 = wall[g] + out(g, 3);
    gallery = box3(x0, b.y0, b.z0 - 1, x1, b.y0, b.z1 + 1);
  }
  const seatXZ = SIDES[g].axis === 'z' ? at(g, mid.x, 1) : at(g, mid.z, 1);
  const seat = { x: seatXZ.x + 0.5, y: b.y0 + 1, z: seatXZ.z + 0.5, yaw: ((SIDES[g].yaw + 360) % 360) - 180, pitch: 10 };
  const wallBox = box3(b.x0 - 1, b.y0 - 1, b.z0 - 1, b.x1 + 1, top + 1, b.z1 + 1);
  const footprint = [wallBox, box3(gallery.x0, gallery.y0, gallery.z0, gallery.x1, gallery.y0 + 2, gallery.z1),
    box3(boardAt.x, b.y0, boardAt.z, boardAt.x, b.y0 + 3, boardAt.z), box3(pylonAt.x, b.y0, pylonAt.z, pylonAt.x, b.y0 + 2, pylonAt.z)];
  return {
    top, wall, door, gallery, seat, footprint,
    board: { x: boardAt.x + 0.5, y: b.y0 + Math.min(b.h, 4) + 0.6, z: boardAt.z + 0.5 },
    pylon: { x: pylonAt.x, y: b.y0, z: pylonAt.z },
  };
}

/** The volumes of a cell that must be air when it is as built. */
function cellClear(ch) {
  const out = [interior(ch.box)];
  if (ch.shaft) out.push(box3(ch.box.x0, ch.box.y0 - ch.shaft, ch.box.z0, ch.box.x1, ch.box.y0 - 2, ch.box.z1));
  return out;
}

/** A cell's enclosure: walls (glass on the gallery side), roof, doorway, hazard threshold. */
function cellShell(bp, ch, colour) {
  const b = ch.box;
  const L = cellLayout(ch);
  const top = L.top;
  const glassSide = ch.gallery;
  const walls = {
    n: box3(b.x0 - 1, b.y0, b.z0 - 1, b.x1 + 1, top, b.z0 - 1),
    s: box3(b.x0 - 1, b.y0, b.z1 + 1, b.x1 + 1, top, b.z1 + 1),
    w: box3(b.x0 - 1, b.y0, b.z0, b.x0 - 1, top, b.z1),
    e: box3(b.x1 + 1, b.y0, b.z0, b.x1 + 1, top, b.z1),
  };
  for (const side of ['n', 's', 'w', 'e']) bp.fill(walls[side], side === glassSide ? P.cellGlass : P.cellWall);
  bp.fill(box3(b.x0 - 1, top + 1, b.z0 - 1, b.x1 + 1, top + 1, b.z1 + 1), P.roof);
  // A coloured band at the top of the solid walls says which department the cell belongs to.
  for (const side of ['n', 's', 'w', 'e']) {
    if (side === glassSide || b.h < 4) continue;
    const w = walls[side];
    bp.fill({ ...w, y0: top, y1: top }, `minecraft:${colour}_concrete`);
  }
  if (ch.shaft) {
    const s = box3(b.x0 - 1, b.y0 - ch.shaft, b.z0 - 1, b.x1 + 1, b.y0 - 1, b.z1 + 1);
    bp.fill(s, 'minecraft:air');
    bp.fill({ ...s, y0: s.y0 - 1, y1: s.y0 - 1 }, P.cellWall);
    for (let depth = 20; depth < ch.shaft; depth += 20) {
      bp.fill(box3(b.x0 - 1, b.y0 - depth - 1, b.z0 - 1, b.x1 + 1, b.y0 - depth - 1, b.z0 - 1), P.gallery);
    }
    // A glass cap until the chamber has logic, so nobody walks into a 60-block drop.
    bp.fill(box3(b.x0 - 1, b.y0 - 1, b.z0 - 1, b.x1 + 1, b.y0 - 1, b.z1 + 1), 'minecraft:glass');
  }
  // The doorway and its hazard threshold last, so a shaft's glass cap does not cover the threshold.
  for (const [i, d] of L.door.blocks.entries()) {
    bp.fill(box3(d.x, b.y0, d.z, d.x, b.y0 + L.door.height - 1, d.z), 'minecraft:air');
    bp.set(d.x, b.y0 - 1, d.z, i % 2 ? P.hazardB : P.hazardA);
  }
  bp.anchor(walls.n.x0, b.y0 + 1, walls.n.z0, glassSide === 'n' ? P.cellGlass : P.cellWall, `${ch.id} north wall`);
}

/** The parts of a cell outside its enclosure: gallery, railing, steps, pylon base. */
function cellSurrounds(bp, ch) {
  const L = cellLayout(ch);
  const g = L.gallery;
  bp.fill(g, ch.galleryFloor || P.gallery);
  const outer = SIDES[ch.gallery].axis === 'z'
    ? box3(g.x0, g.y0 + 1, ch.gallery === 'n' ? g.z0 : g.z1, g.x1, g.y0 + 1, ch.gallery === 'n' ? g.z0 : g.z1)
    : box3(ch.gallery === 'w' ? g.x0 : g.x1, g.y0 + 1, g.z0, ch.gallery === 'w' ? g.x0 : g.x1, g.y0 + 1, g.z1);
  bp.fill(outer, P.rail);
  bp.fill(box3(L.pylon.x, L.pylon.y, L.pylon.z, L.pylon.x, L.pylon.y + 1, L.pylon.z), P.pylonBase);
  bp.set(L.pylon.x, L.pylon.y + 2, L.pylon.z, 'minecraft:gray_concrete');
  bp.anchor(L.pylon.x, L.pylon.y + 2, L.pylon.z, 'minecraft:gray_concrete', `${ch.id} pylon`);
}

/** A desk: three copper blocks, a pylon at one end. */
function desk(bp, ch) {
  const { x, y, z } = ch.at;
  bp.fill(box3(x - 1, y, z, x + 1, y, z), P.console);
  bp.fill(box3(x + 2, y, z, x + 2, y + 1, z), P.pylonBase);
  bp.set(x + 2, y + 2, z, 'minecraft:gray_concrete');
  bp.anchor(x, y, z, P.console, `${ch.id} desk`);
}

function deskLayout(ch) {
  const { x, y, z } = ch.at;
  return {
    board: { x: x + 0.5, y: y + 2.4, z: z + 0.5 },
    pylon: { x: x + 2, y, z },
    seat: { x: x + 0.5, y, z: z + 2.5, yaw: 180, pitch: 10 },
    footprint: [box3(x - 1, y, z, x + 2, y + 3, z)],
  };
}

/** Board, pylon and seat for any chamber, whatever its kind. */
function layoutOf(ch) {
  if (ch.kind === 'cell') return cellLayout(ch);
  if (ch.kind === 'desk') return deskLayout(ch);
  const b = ch.box; // a tunnel: board at its mouth
  return {
    board: { x: b.x0 + 2.5, y: b.y0 + 3.2, z: Math.floor((b.z0 + b.z1) / 2) + 0.5 },
    pylon: null,
    seat: { x: b.x0 + 1.5, y: b.y0, z: Math.floor((b.z0 + b.z1) / 2) + 0.5, yaw: -90, pitch: 0 },
    footprint: [box3(b.x0, b.y0 - 1, b.z0 - 1, b.x1, b.y0 + b.h, b.z1 + 1)],
  };
}

// ---- plates and boards ---------------------------------------------------------------------

/** A stone pressure plate on an impulse command block that sends whoever stands on it. */
function plate(bp, x, y, z, dest) {
  const d = campus.wing(dest.wing || dest);
  const to = dest.to || d.entrance;
  const dim = dest.dim || d.dim;
  const command = `execute as @p[distance=..2] in ${dim} run tp @s ${to.x} ${to.y} ${to.z} ${to.yaw || 0} 0`;
  bp.set(x, y - 1, z, `minecraft:command_block{Command:"${command}",TrackOutput:0b}`);
  bp.set(x, y, z, 'minecraft:stone_pressure_plate');
  bp.anchor(x, y, z, 'minecraft:stone_pressure_plate', `plate to ${dest.wing || dest}`);
}

function boardTags(id, wingId) {
  return ['wx_board', `wx_board_${id}`, `wx_wing_${wingId}`];
}

/** A `summon` for a board; the text is the version's own form (see text.js). */
function summonBoard(version, { id, wing: wingId, at, spec, scale = 1 }) {
  return text.summonDisplay(version, {
    x: at.x, y: at.y, z: at.z, tags: boardTags(id, wingId), spec,
    nbt: { billboard: '"center"', see_through: '0b', ...(scale !== 1 ? { transformation: `{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[${scale}f,${scale}f,${scale}f]}` } : {}) },
  });
}

/** The text a chamber's board shows before it has ever run. */
function chamberBoardSpec(ch) {
  const w = campus.wing(ch.wing);
  const status = ch.logic
    ? { text: 'idle · never run', color: 'gray' }
    : { text: `not built yet · stage ${ch.stage}`, color: 'dark_gray' };
  return [{ text: `${ch.id.toUpperCase()} `, color: w.text, bold: true }, { text: ch.title, color: 'white', bold: true }, '\n', status];
}

// ---- decoration vocabulary (stage 3.6) --------------------------------------------------------
//
// Pure functions over a Blueprint, used inside `decorate`, so the guardrail sees every block they
// write. Nothing here may reach a cell, a gate or ring or pad footprint, a lane or a keep-clear box.

/** One-wide floor lines between consecutive [x, z] points, axis-aligned; throws on a diagonal. */
function stripe(bp, points, colour, y = -1) {
  const block = colour.includes(':') ? colour : `minecraft:${colour}_concrete`;
  for (let i = 1; i < points.length; i++) {
    const [ax, az] = points[i - 1];
    const [bx, bz] = points[i];
    if (ax !== bx && az !== bz) throw new Error(`stripe ${JSON.stringify(points)}: ${ax},${az} to ${bx},${bz} is diagonal`);
    bp.fill(box3(ax, y, az, bx, y, bz), block);
  }
}

/** A floor pattern: `cells` are [dx, dz, block] from (x, z) at height y. */
function inlay(bp, { x, z, y = -1 }, cells) {
  for (const [dx, dz, block] of cells) bp.set(x + dx, y, z + dz, block);
}

/** A column `h` high from y0, and its cap on top (an anchor, so the self-test reads it back). */
function pillar(bp, x, z, y0, h, { body = P.console, cap = P.guide } = {}) {
  if (h > 0) bp.fill(box3(x, y0, z, x, y0 + h - 1, z), body);
  if (cap) {
    bp.set(x, y0 + h, z, cap);
    bp.anchor(x, y0 + h, z, cap, `pillar cap at ${x} ${y0 + h} ${z}`);
  }
}

/**
 * A console along `axis` ('x' or 'z') from (x, y, z): one block per button, each a command block
 * with a stone button on top that runs its command, and a small display over it. `plain` entries
 * (no command) are copper blocks.
 */
function controlConsole(bp, version, { x, y, z, wing }, axis, buttons) {
  buttons.forEach((b, i) => {
    const bx = axis === 'x' ? x + i : x;
    const bz = axis === 'z' ? z + i : z;
    if (!b.command) {
      bp.set(bx, y, bz, P.console);
    } else {
      bp.set(bx, y, bz, `minecraft:command_block{Command:${text.quoteSingle(b.command)},TrackOutput:0b}`);
      bp.set(bx, y + 1, bz, 'minecraft:stone_button[face=floor,facing=south]');
    }
    if (b.label) bp.cmd(summonBoard(version, { id: `console_${bx}_${bz}`, wing, at: { x: bx + 0.5, y: y + 1.9, z: bz + 0.5 }, spec: [{ text: b.label, color: b.color || 'aqua', bold: true }] }));
  });
}

/**
 * A runway on the arrival side of a gate: `length` rows, `half` either side of the opening's
 * centre, starting one row past the DHD button so it never touches the gate's own blocks.
 */
function runway(bp, geom, length, { block = 'minecraft:deepslate_bricks', half = 1, floorY = 0 } = {}) {
  const n = geom.normal;
  const along = n.x !== 0 ? 'x' : 'z';
  const sign = n.x !== 0 ? n.x : n.z;
  const start = geom.button[along] + sign;
  const end = start + sign * (length - 1);
  const c = Math.floor(along === 'z' ? geom.centre.x : geom.centre.z);
  const b = along === 'z' ? box3(c - half, floorY - 1, start, c + half, floorY - 1, end) : box3(start, floorY - 1, c - half, end, floorY - 1, c + half);
  bp.fill(b, block);
  return b;
}

/**
 * A deck: a floor at y over `box` (x0..x1, z0..z1), iron-bar railing one up on `rail` sides,
 * `light` blocks in its underside every four, and optionally a stair { x0, x1, z, dir } rising
 * towards the deck along z.
 */
function deck(bp, box, y, { rail = [], stair = null, floor = 'minecraft:deepslate_tiles' } = {}) {
  bp.fill(box3(box.x0, y, box.z0, box.x1, y, box.z1), floor);
  const edge = {
    n: box3(box.x0, y + 1, box.z0, box.x1, y + 1, box.z0), s: box3(box.x0, y + 1, box.z1, box.x1, y + 1, box.z1),
    w: box3(box.x0, y + 1, box.z0, box.x0, y + 1, box.z1), e: box3(box.x1, y + 1, box.z0, box.x1, y + 1, box.z1),
  };
  for (const side of rail) bp.fill(edge[side], P.rail);
  for (let x = box.x0 + 1; x < box.x1; x += 4) {
    for (let z = box.z0 + 1; z < box.z1; z += 4) bp.set(x, y - 1, z, 'minecraft:light[level=15]');
  }
  if (stair) {
    // Rising north (towards smaller z) from the ground to the deck: one step per row.
    for (let k = 0; k < y; k++) {
      const z = stair.z - k;
      bp.fill(box3(stair.x0, k, z, stair.x1, k, z), 'minecraft:deepslate_tile_stairs[facing=north]');
      if (k > 0) bp.fill(box3(stair.x0, 0, z, stair.x1, k - 1, z), P.gallery);
    }
  }
}

/** A small display: sugar over summonBoard. */
function plaque(version, { id, wing, at, text: words, colour = 'white', scale = 0.8, sub = null }) {
  const spec = [{ text: words, color: colour, bold: true }];
  if (sub) spec.push('\n', { text: sub, color: 'gray' });
  return summonBoard(version, { id: `plaque_${id}`, wing, at, spec, scale });
}

/**
 * A wall banner (stage 4's mirrors) with the wall rule checked against this blueprint's own ops:
 * the block behind it and the border one out must be written solid here.
 */
function banner(bp, x, y, z, facing, colour = 'white') {
  const back = { north: [0, 1], south: [0, -1], west: [1, 0], east: [-1, 0] }[facing];
  // The last op to write the block decides it: a fill of air after a solid one leaves air.
  const solid = (bx, by, bz) => {
    const last = [...bp.ops].reverse().find((o) => (o.kind === 'fill'
      && bx >= o.box.x0 && bx <= o.box.x1 && by >= o.box.y0 && by <= o.box.y1 && bz >= o.box.z0 && bz <= o.box.z1)
      || (o.kind === 'set' && o.at[0] === bx && o.at[1] === by && o.at[2] === bz));
    return Boolean(last) && !/^minecraft:(cave_|void_)?air$/.test(last.block);
  };
  const wx = x + back[0];
  const wz = z + back[1];
  for (const dy of [-1, 0, 1]) {
    if (!solid(wx, y + dy, wz)) throw new Error(`banner at ${x} ${y} ${z}: no solid wall at ${wx} ${y + dy} ${wz}`);
  }
  bp.set(x, y, z, `minecraft:${colour}_wall_banner[facing=${facing}]`);
  bp.anchor(x, y, z, `minecraft:${colour}_wall_banner`, `banner at ${x} ${y} ${z}`);
}

module.exports = {
  FILL_LIMIT, box3, volume, split, overlaps, interior, Blueprint, room, corridor, corridorDoorways, cellLayout, cellClear,
  cellShell, cellSurrounds, desk, deskLayout, layoutOf, plate, summonBoard, boardTags, chamberBoardSpec, SIDES,
  stripe, inlay, pillar, console: controlConsole, runway, deck, plaque, banner,
};
