'use strict';
// Writes the facility's datapack into <world>/datapacks/wx/. The layout changed twice inside
// the supported range: the function folder lost its plural at 1.21, and pack.mcmeta gained
// min_format/max_format (with major.minor formats) at 1.21.9.

const fs = require('fs');
const path = require('path');
const { atLeast, compare } = require('./version');

// Data pack format per release, oldest first. Checked against the vanilla jar's version.json:
// 1.20.4 = 26, 1.21.11 = 94.1, 26.1.2 = 101.1; spike.js cross-checks it on every run.
const PACK_FORMATS = [
  ['1.20', 15], ['1.20.2', 18], ['1.20.3', 26], ['1.20.5', 41], ['1.21', 48], ['1.21.2', 57],
  ['1.21.4', 61], ['1.21.5', 71], ['1.21.6', 80], ['1.21.7', 81], ['1.21.9', 88],
  ['1.21.11', [94, 1]], ['26.1', [101, 1]],
];

const OLDEST_FORMAT = 15;
const NEWEST_FORMAT = 999;

/** The data pack format for a version: a number, or [major, minor] from 1.21.9's scheme. */
function packFormat(version) {
  let found = null;
  for (const [from, format] of PACK_FORMATS) if (compare(version, from) >= 0) found = format;
  if (found === null) throw new Error(`no data pack format known for ${version}`);
  return found;
}

function major(format) {
  return Array.isArray(format) ? format[0] : format;
}

/**
 * pack.mcmeta for a version. Old servers read pack_format and supported_formats; from 1.21.9
 * servers read min_format and max_format and, for a range that reaches back past 82, also
 * require the old two fields, so all four are written with one wide range.
 */
function packMeta(version) {
  const format = packFormat(version);
  return {
    pack: {
      description: 'Wormhole Research Facility',
      pack_format: major(format),
      supported_formats: { min_inclusive: OLDEST_FORMAT, max_inclusive: NEWEST_FORMAT },
      min_format: OLDEST_FORMAT,
      max_format: NEWEST_FORMAT,
    },
  };
}

function functionFolder(version) {
  return atLeast(version, '1.21') ? 'function' : 'functions';
}

/**
 * A hollow box, then the sentinel block last: the bot waits for the sentinel, so a function
 * that stops early (a bad line is skipped, not fatal, on some versions) never reads as built.
 */
function boxFunction({ from, to, block, sentinel }) {
  const [x0, y0, z0] = from;
  const [x1, y1, z1] = to;
  return [
    `# wx:build/box, generated by scripts/facility/lib/datapack.js`,
    `fill ${x0} ${y0} ${z0} ${x1} ${y1} ${z1} ${block} hollow`,
    `setblock ${sentinel.at.join(' ')} ${sentinel.block}`,
    '',
  ].join('\n');
}

/** Writes the pack, replacing any earlier one; returns the pack folder. */
function writePack(worldFolder, version, functions) {
  const root = path.join(worldFolder, 'datapacks', 'wx');
  fs.rmSync(root, { recursive: true, force: true });
  const fnRoot = path.join(root, 'data', 'wx', functionFolder(version));
  for (const [name, body] of Object.entries(functions)) {
    const file = path.join(fnRoot, `${name}.mcfunction`);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
  }
  fs.writeFileSync(path.join(root, 'pack.mcmeta'), `${JSON.stringify(packMeta(version), null, 2)}\n`);
  return root;
}

module.exports = { PACK_FORMATS, packFormat, packMeta, functionFolder, boxFunction, writePack };
