"""Regenerate src/main/resources/shapes/shipped-shapes.txt from git history.

Every revision of a bundled gate shape that main has ever held, under any path, is hashed the
way ShippedShapes.hash does: SHA-256 of the text with every line ended by a single LF.
Run it from the repository root after changing a bundled shape; ShippedShapesTest fails until
the list holds the shape as it ships now.
"""
import hashlib
import pathlib
import re
import subprocess

LIST = pathlib.Path("src/main/resources/shapes/shipped-shapes.txt")
SOURCE = pathlib.Path("src/main/java/com/wormhole_xtreme/wormhole/model/ShippedShapes.java")
HEADER = """# Every version of each bundled gate shape the plugin has shipped, as SHA-256 of the
# file with LF line endings. A server copy matching one of these was never edited, so
# startup replaces it with the current version. Generated by scripts/shipped_shapes.py.
"""


def git(*args):
    return subprocess.run(["git", *args], check=True, capture_output=True).stdout


def normalised_hash(data):
    text = data.decode("utf-8")
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    if lines and lines[-1] == "":
        lines.pop()
    return hashlib.sha256("".join(line + "\n" for line in lines).encode("utf-8")).hexdigest()


def main():
    names = re.findall(r'"(\w+\.shape)"', SOURCE.read_text(encoding="utf-8").split("NAMES", 1)[1].split(";", 1)[0])
    # Blobs of every non-test .shape path main has touched, oldest first.
    log = git("log", "main", "--reverse", "--format=%H", "--name-only", "--", "*.shape").decode()
    seen = {}
    commit = None
    for line in log.splitlines():
        if re.fullmatch(r"[0-9a-f]{40}", line):
            commit = line
        elif line.endswith(".shape") and not line.startswith("src/test"):
            name = line.rsplit("/", 1)[-1]
            if name not in names:
                continue
            try:
                data = git("show", f"{commit}:{line}")
            except subprocess.CalledProcessError:
                continue  # deleted in this commit
            seen.setdefault(name, {})[normalised_hash(data)] = None
    # The working tree's copy too, so a shape changed on this branch is listed before it merges.
    for name in names:
        data = pathlib.Path("src/main/resources/shapes/gate", name).read_bytes()
        seen.setdefault(name, {})[normalised_hash(data)] = None
    body = "".join(f"{name} {digest}\n" for name in names for digest in seen.get(name, {}))
    LIST.write_bytes((HEADER + body).encode("utf-8"))
    print(f"{LIST}: {body.count(chr(10))} versions of {len(names)} shapes")


if __name__ == "__main__":
    main()
